name: Build AAB
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
 
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
 
      - name: Fix Android embedding
        run: flutter create --org com.tarotify --project-name tarotify --platforms android .
 
      - name: Get dependencies
        run: flutter pub get
 
      - name: Build AAB
        run: flutter build appbundle --release
 
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: tarotify-release
          path: build/app/outputs/bundle/release/app-release.aab
